[id='proc-changing-topic-configuration-{context}']
= Changing topic configuration

[role="_abstract"]
Change the configuration of a specific topic from the *Configuration* tab.
The *Configuration* tab presents a list of configuration options for the topic.

The topics are configured directly in the Kafka cluster.
If you are using the Topic Operator to manage topics in unidirectional mode, configure the topics using `KafkaTopic` resources outside the console.

.Procedure

. Log in to the Kafka cluster in the StreamsHub Console, then click *Topics*.
. Select the options icon (three vertical dots) for the relevant topic and click *Edit configuration*.
Or you can click the name of the topic you want to configure from the *Topics* page and click the *Configuration* tab.
. Edit the configuration by updating individual property values.
You can filter for the properties you want to configure, including selecting by data source:
+
* *DEFAULT_CONFIG* properties have a predefined default value. This value is used when there are no user-defined values for those properties. 
* *STATIC_BROKER_CONFIG* properties have predefined values that apply to the entire broker and, by extension, to all topics managed by that broker. This value is used when there are no user-defined values for those properties. 
* *DYNAMIC_TOPIC_CONFIG* property values have been configured for a specific topic and override the default configuration values.
