:_mod-docs-content-type: PROCEDURE

[id='proc-changing-topic-configuration-{context}']
= Changing topic configuration

[role="_abstract"]
Change the configuration of a specific topic from the *Configuration* tab.
The *Configuration* tab lists the configuration options for the topic.

The topics are configured directly in the Kafka cluster.
If you are using the Topic Operator to manage topics in unidirectional mode, configure the topics using `KafkaTopic` resources outside the console.

.Procedure

. Log in to the Kafka cluster in the StreamsHub Console, then click *Topics*.
. Select the options icon (three vertical dots) for the relevant topic and click *Edit configuration*.
Or you can click the name of the topic you want to configure from the *Topics* page and click the *Configuration* tab.
. Edit the configuration by updating individual property values.
+
Filter the configuration properties to narrow results by data source:
+
* *DEFAULT_CONFIG*: The fallback value used when no other configuration is specified.
* *STATIC_BROKER_CONFIG*: Predefined, broker-wide values that apply to all topics by default.
* *DYNAMIC_TOPIC_CONFIG*: Topic-specific values that override all default or broker-level settings.
