:_mod-docs-content-type: PROCEDURE

[id='proc-creating-topics-{context}']
= Creating topics

[role="_abstract"]
Create topics from the *Topics* page.

.Procedure

. Log in to the Kafka cluster in the StreamsHub Console, then click *Topics* and *Create topic*.
. Set core configuration, such as the name of the topic, and the number of topic partitions and replicas.
. (Optional) Specify additional configuration, such as the following: 
+
* Size-based and time-based message retention policies
* Maximum message size and compression type
* Log indexing, and cleanup and flushing of old data

. Review your topic configuration, then click *Create topic*.
+
The topics are created directly in the Kafka cluster without using `KafkaTopic` custom resources. 
If you are using the Topic Operator to manage topics in unidirectional mode, create the topics using `KafkaTopic` resources outside the console.
+
For more information on topic configuration properties, see the {kafkaDoc}. 
+
NOTE: For topic replication, partition leader elections can be clean or unclean. 
Clean leader election means that out-of-sync replicas cannot become leaders. 
If no in-sync replicas are available, Kafka waits until the original leader is back online before messages are picked up again. 
