kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-server
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkaconnectors
      - kafkaconnects
      - kafkamirrormaker2s
      - kafkanodepools
      - kafkarebalances
      - kafkatopics
      - kafkausers
  - verbs:
      - patch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkarebalances
  # API must list pods to obtain the Kafka version annotation set by Strimzi
  - verbs:
      - get
      - list
    apiGroups:
      - ""
    resources:
      - pods
  # API may read the ClusterVersion to fetch the OpenShift version for display
  - verbs:
      - get
    apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    resourceNames:
      - version
