apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      serviceAccountName: console-server
      volumes:
      - name: cache
        emptyDir: {}
      - name: config
        secret:
          secretName: console-config
      containers:
      ### API
      - name: console-api
        image: quay.io/streamshub/console-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /deployments/console-config.yaml
          subPath: console-config.yaml
        env:
        - name: CONSOLE_CONFIG_PATH
          value: /deployments/console-config.yaml
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
      ### User Interface
      - name: console-ui
        image: quay.io/streamshub/console-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: cache
          mountPath: /app/.next/cache
        env:
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: console-ui-secrets
              key: NEXTAUTH_SECRET
        - name: NEXTAUTH_URL
          value: 'https://${CONSOLE_HOSTNAME}'
        - name: BACKEND_URL
          value: 'http://127.0.0.1:8080'
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
