FROM quay.io/apicurio/apicurio-registry-mem:2.6.13.Final
# No operations, this is only a placeholder used to manage the image
# version via dependabot. The FROM statement is always expected to
# present on the first line of this file.
