FROM quay.io/strimzi-test-container/test-container:0.109.1-kafka-3.9.0
# No operations, this is only a placeholder used to manage the image
# version via dependabot. The FROM statement is always expected to
# present on the first line of this file.
