#!/usr/bin/env bash
# Generates console configuration from the live cluster. Source, don't execute.
# Depends on common.sh and infra.sh already being sourced.
#
#  generate_console_config -> .gen/console-config.yaml  (for host-run quarkus:dev)
#  generate_console_cr     -> .gen/console-cr.yaml       (for operator mode)

# console-config.yaml for a locally-run API (frontend/backend modes). Reaches
# the in-cluster Kafka over the `secure` listener via the ingress, using the
# SCRAM password and cluster CA pulled straight from the live cluster.
generate_console_config() {
  ensure_context
  load_state
  mkgen

  local pw domain https_port bootstrap cfg
  pw="$(kubectl -n "${KAFKA_NAMESPACE}" get secret "${KAFKA_USER}" -o jsonpath='{.data.password}' 2>/dev/null | base64 -d || true)"
  [ -n "${pw}" ] || die "SCRAM secret '${KAFKA_USER}' not found in namespace '${KAFKA_NAMESPACE}'.
  Is the environment up and Kafka Ready? Run: ${DEV_DIR}/dev.sh up"

  # NOTE: we deliberately do NOT configure ssl.truststore here. With
  # kubernetes.enabled the console discovers the Strimzi Kafka resource and
  # injects the cluster CA as trust certificates itself; also specifying a
  # truststore location makes the Kafka admin client fail with "Both SSL trust
  # store location and separate trust certificates are specified."

  domain="${CONSOLE_CLUSTER_DOMAIN}"
  https_port="${INGRESS_HTTPS_PORT:-443}"
  bootstrap="bootstrap.${KAFKA_NAME}.${domain}:${https_port}"
  cfg="${GEN_DIR}/console-config.yaml"

  {
    echo "# Generated by dev.sh from the live cluster — do not edit."
    echo "# Regenerate with: dev.sh config"
    echo "kubernetes:"
    echo "  enabled: true"

    if has_profile keycloak; then
cat <<EOF
security:
  oidc:
    authServerUrl: http://keycloak.${domain}/realms/streamshub
    clientId: streamshub-console-client
    clientSecret: streamshub-console-secret
  subjects:
    - claim: groups
      include: [ administrators ]
      roleNames: [ administrators ]
    - claim: groups
      include: [ developers ]
      roleNames: [ developers ]
  roles:
    # NOTE: resource '*' is accepted by config validation but is NOT expanded at
    # runtime — PermissionCache matches the possessed resource string against the
    # required one by exact equality, so '*' matches nothing and denies everything.
    # Always list resources explicitly ('*' is only meaningful for privileges).
    - name: administrators
      rules:
        - resources: [ kafkas ]
          privileges: [ '*' ]
    - name: developers
      rules:
        - resources: [ kafkas ]
          privileges: [ GET, LIST ]
EOF
    fi

    if has_profile metrics; then
cat <<EOF
metricsSources:
  - name: dev-prometheus
    type: standalone
    url: http://prometheus.${domain}
EOF
    fi

    if has_profile registry; then
cat <<EOF
schemaRegistries:
  - name: dev-registry
    url: http://registry.${domain}/apis/registry/v2/
EOF
    fi

    echo "kafka:"
    echo "  clusters:"
    echo "    - name: ${KAFKA_NAME}"
    echo "      namespace: ${KAFKA_NAMESPACE}"
    echo "      listener: secure"
    has_profile metrics  && echo "      metricsSource: dev-prometheus"
    has_profile registry && echo "      schemaRegistry: dev-registry"
cat <<EOF
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        bootstrap.servers: ${bootstrap}
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER}" password="${pw}";
EOF
    if has_profile keycloak; then
cat <<EOF
      security:
        roles:
          # Explicit resource lists (see note above — '*' resources match nothing
          # at runtime). 'users' must be listed for the Kafka Users view to work.
          - name: administrators
            rules:
              - resources: [ topics, topics/records, topics/metrics, groups, groups/configs, nodes, nodes/configs, nodes/metrics, rebalances, users ]
                privileges: [ '*' ]
          - name: developers
            rules:
              - resources: [ topics, topics/records, topics/metrics, groups, nodes, rebalances ]
                privileges: [ GET, LIST ]
EOF
    fi

    if has_profile connect; then
cat <<EOF
kafkaConnectClusters:
  - name: dev-connect
    url: http://connect.${domain}
    kafkaClusters:
      - ${KAFKA_NAMESPACE}/${KAFKA_NAME}
EOF
    fi
  } > "${cfg}"

  step "Wrote ${cfg}"
}

# Console CR for operator mode. The console runs IN-CLUSTER, so it uses the
# `plain` internal listener (no credentials needed) and internal Service DNS
# for Prometheus/Apicurio/Connect. OIDC is intentionally omitted here — an
# in-cluster console needs the Keycloak issuer URL to resolve to the ingress,
# which needs extra DNS wiring (see dev/README.md); use frontend/backend mode
# to exercise the login flow.
generate_console_cr() {
  load_state
  mkgen
  local domain cr
  domain="${CONSOLE_CLUSTER_DOMAIN}"
  cr="${GEN_DIR}/console-cr.yaml"
  {
    echo "# Generated by dev.sh — applied by 'dev.sh operator'."
    echo "apiVersion: console.streamshub.github.com/v1alpha1"
    echo "kind: Console"
    echo "metadata:"
    echo "  name: example"
    echo "spec:"
    echo "  hostname: example-console.${domain}"
    if has_profile metrics; then
cat <<EOF
  metricsSources:
    - name: dev-prometheus
      type: standalone
      url: http://console-prometheus.metrics.svc:9090
EOF
    fi
    if has_profile registry; then
cat <<EOF
  schemaRegistries:
    - name: dev-registry
      url: http://apicurio-registry.registry.svc:8080/apis/registry/v2/
EOF
    fi
    echo "  kafkaClusters:"
    echo "    - name: ${KAFKA_NAME}"
    echo "      namespace: ${KAFKA_NAMESPACE}"
    echo "      listener: plain"
    has_profile metrics  && echo "      metricsSource: dev-prometheus"
    has_profile registry && echo "      schemaRegistry: dev-registry"
    if has_profile connect; then
cat <<EOF
  kafkaConnectClusters:
    - name: dev-connect
      url: http://console-connect-connect-api.${KAFKA_NAMESPACE}.svc:8083
      kafkaClusters:
        - ${KAFKA_NAMESPACE}/${KAFKA_NAME}
EOF
    fi
  } > "${cr}"
  step "Wrote ${cr}"
}
