name = STConfig

rootLogger.additivity = false

logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN

logger.fabric8.name = io.fabric8.kubernetes.client
logger.fabric8.level = OFF
logger.jayway.name = com.jayway.jsonpath.internal.path.CompiledPath
logger.jayway.level = OFF
