package com.github.streamshub.systemtests.unit.utils;

class SetupUtilsTest {
    // TODO
    // @Test
    // void testGetYamlFileContent() {
    //     String invalidUrl = "http://very-invalid-123.cy/test.yaml";
    //     String validUrl = "https://github.com/streamshub/console/releases/download/0.6.3/streamshub-console-operator.yaml";
    //
    //     Exception exception = assertThrows(RuntimeException.class, () -> FileUtils.getYamlContentFromUrl(invalidUrl));
    //     assertTrue(exception.getMessage().contains("Cannot download YAML content"));
    //
    //     assertTrue(FileUtils.getYamlContentFromUrl(validUrl).startsWith("# Generated by Fabric8 CRDGenerator, manual edits might get overwritten!"));
    // }
}

