package com.github.streamshub.systemtests.unit.utils;

import com.github.streamshub.systemtests.utils.SetupUtils;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SetupUtilsTest {

    @Test
    void testGetYamlFileContent() {
        String invalidUrl = "http://very-invalid-123.cy/test.yaml";
        String validUrl = "https://github.com/streamshub/console/releases/download/0.6.3/streamshub-console-operator.yaml";

        Exception exception = assertThrows(RuntimeException.class, () -> SetupUtils.getYamlFileContent(invalidUrl));
        assertTrue(exception.getMessage().contains("Cannot download YAML content"));

        assertTrue(SetupUtils.getYamlFileContent(validUrl).startsWith("# Generated by Fabric8 CRDGenerator, manual edits might get overwritten!"));
    }
}

