:_mod-docs-content-type: REFERENCE

// Module included in the following assemblies:
//
// assembly-deploying.adoc

[id='ref-authentication-options-{context}']
= Using an OIDC provider to secure access to Kafka clusters

[role="_abstract"]
Enable secure console connections to Kafka clusters using an OIDC provider.
Configure the console deployment to configure connections to any Identity Provider (IdP), such as Keycloak or Dex, that supports OpenID Connect (OIDC).
Also define the subjects and roles for user authorization.
To use group-based authorization as shown in the examples, the configured OIDC provider must support the `groups` scope to include a user's group membership in the generated access tokens.
The security profiles can be configured for all Kafka cluster connections on a global level, though you can add roles and rules for specific Kafka clusters.

An example configuration is provided in the following file: `examples/console/console-security-oidc.yaml`.

The configuration introduces the following additional properties for console deployment:

`security`:: Properties that define the connection details for the console to connect with the OIDC provider.
`subjects`:: Specifies the subjects (users or groups) and their roles in terms of JWT claims or explicit subject names, determining access permissions.
`roles`:: Defines the roles and associated access rules for users, specifying which resources (like Kafka clusters) they can interact with and what operations they are permitted to perform.

.Example security configuration for all clusters
[source,yaml]
----
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: my-console
spec:
  hostname: my-console.<cluster_domain>
  security:
    oidc:
      authServerUrl: <OIDC_discovery_URL> # <1>
      clientId: <client_id> # <2>
      clientSecret: # <3>
        valueFrom:
          secretKeyRef:
            name: my-oidc-secret # <4>
            key: client-secret # <5>
      trustStore: # <6>
        type: JKS
        content:
          valueFrom:
            configMapKeyRef:
              name: my-oidc-configmap
              key: ca.jks
        password: # <7>
          value: truststore-password
    subjects:
      - claim: groups # <8>
        include: # <9>
          - <team_name_1>
          - <team_name_2>
        roleNames: # <10>
          - developers
      - claim: groups
        include:
          - <team_name_3>
        roleNames:
          - administrators
      - include: #<11>
          - <user_1>
          - <user_2>
        roleNames:
          - administrators
    roles:
      - name: developers
        rules:
          - resources: # <12>
              - kafkas
            resourceNames: # <13>
              - <dev_cluster_a>
              - <dev_cluster_b>
            privileges: # <14>
              - '*'
      - name: administrators
        rules:
          - resources:
              - kafkas
            privileges:
              - '*'
  kafkaClusters:
    - name: console-kafka
      namespace: kafka
      listener: secure
      credentials:
        kafkaUser:
          name: console-kafka-user1

----
<1> The OIDC provider's issuer URI for endpoint discovery.
<2> The client ID that identifies the console to the OIDC provider. This value is obtained from the client credentials in your OIDC provider.
<3> The client secret, which authenticates the client when used with the client ID. This value is also obtained from the client credentials in your OIDC provider.
<4> The name of the Kubernetes `Secret` where the client secret is stored.
<5> The key within the `Secret` that holds the client secret value.
<6> Optional truststore used to validate the OIDC provider’s TLS certificate. Supported formats include `JKS`, `PEM`, and `PKCS12`. Truststore content can be provided using either a `ConfigMap` (`configMapKeyRef`) or a `Secret` (`secretKeyRef`).
<7> Optional password for the truststore. Can be provided as a plaintext value (as shown) or more securely by reference to a `Secret`. Plaintext values are not recommended for production.
<8> JWT claim types or names to identify the users or groups.
<9> Users or groups included under the specified claim.
<10> Roles assigned to the specified users or groups.
<11> Specific users included by name when no claim is specified.
<12> Resources that the assigned role can access.
<13> Specific resource names accessible by the assigned role.
<14> Privileges granted to the assigned role for the specified resources.

If you want to specify roles and rules for individual Kafka clusters, add the details under `kafka.clusters[].security.roles[]`.
In the following example, the `console-kafka` cluster allows developers to list and view selected Kafka resources.
Administrators can also update certain resources.

.Example security configuration for an individual cluster
[source,yaml]
----
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: my-console
spec:
  hostname: my-console.<cluster_domain>
  # ...
  kafkaClusters:
    - name: console-kafka
      namespace: kafka
      listener: secure
      credentials:
        kafkaUser:
          name: console-kafka-user1
      security:
        roles:
          - name: developers
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                privileges:
                  - GET
                  - LIST
          - name: administrators
            rules:
              - resources:
                  - topics
                  - topics/records
                  - consumerGroups
                  - rebalances
                  - nodes/configs
                privileges:
                  - GET
                  - LIST
              - resources:
                  - consumerGroups
                  - rebalances
                privileges:
                  - UPDATE
----

[discrete]
== Optional OIDC authentication properties

The following properties can be used to further configure `oidc` authentication.
These apply to any part of the console configuration that supports `authentication.oidc`, such as schema registries or metrics providers.

grantType::
Specifies the OIDC grant type to use. Required when using non-interactive authentication flows, where no user login is involved.
Supported values:
+
* `CLIENT`: Requires a client ID and secret.
* `PASSWORD`: Requires a client ID and secret, plus user credentials (`username` and `password`) provided through `grantOptions`.

grantOptions::
Additional parameters specific to the selected grant type.
Use `grantOptions` to provide properties such as `username` and `password` when using the `PASSWORD` grant type.
+
[source,yaml]
----
oidc:
  grantOptions:
    username: my-user
    password: <my_password>
----

method::
Method for passing the client ID and secret to the OIDC provider.
Supported values:
+
* `BASIC`: (default) Uses HTTP Basic authentication.
* `POST`: Sends credentials as form parameters.

scopes::
Optional list of access token scopes to request from the OIDC provider.
Defaults are usually defined by the OIDC client configuration.
Specify this property if access to the target service requires additional or alternative scopes not granted by default.
+
[source,yaml]
----
oidc:
  scopes:
    - openid
    - registry:read
    - registry:write
----

absoluteExpiresIn::
Optional boolean. If set to `true`, the `expires_in` token property is treated as an absolute timestamp instead of a duration.
