package com.github.streamshub.systemtests.locators;

public class ClusterOverviewPageSelectors {
    private ClusterOverviewPageSelectors() {}
    
    public static final String COPS_RECONCILIATION_PAUSED_NOTIFICATION = new CssBuilder(CssSelectors.PAGE_DIV)
        .withChild()
        .withElementDiv().withComponentPage().withChild()
        .withElementDiv().withComponentPage().withSubComponentMainContainer().withChild()
        .withElementMain().withComponentPage().withSubComponentMain().withChild()
        .withElementDiv().withComponentBanner().withChild()
        .withElementDiv().withLayoutBullseye()
        .build();

    public static final String COPS_RECONCILIATION_PAUSED_NOTIFICATION_RESUME_BUTTON = new CssBuilder(COPS_RECONCILIATION_PAUSED_NOTIFICATION)
        .withChild()
        .withElementDiv().withLayoutFlex().withChild()
        .withElementDiv().nth(2).withChild()
        .withElementButton().withComponentButton().withChild()
        .withElementSpan().withComponentButton().withSubComponentText()
        .build();

    public static final String COPS_KAFKA_PAUSE_RECONCILIATION_BUTTON = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(1) > div.pf-v6-c-card > div.pf-v6-c-card__body > div.pf-v6-l-flex:nth-of-type(1) > div:nth-of-type(2) > button.pf-v6-c-button";
    public static final String COPS_CLUSTER_CARD_KAFKA_NAME = "body > div > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(1) > div.pf-v6-c-card > div.pf-v6-c-card__body > div.pf-v6-l-flex:nth-of-type(2) > div.pf-v6-l-flex:nth-of-type(1) > div.pf-v6-l-flex:nth-of-type(1) > div > h2.pf-v6-c-title";

    public static final String COPS_CLUSTER_CARD_KAFKA_DATA_BROKER_COUNT = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(1) > div.pf-v6-c-card > div.pf-v6-c-card__body > div.pf-v6-l-flex:nth-of-type(2) > div.pf-v6-l-flex > div.pf-v6-l-flex:nth-of-type(2) > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > a";

    public static final String COPS_CLUSTER_CARD_KAFKA_DATA_KAFKA_VERSION = "body > div > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(1) > div.pf-v6-c-card > div.pf-v6-c-card__body > div.pf-v6-l-flex:nth-of-type(2) > div.pf-v6-l-flex:nth-of-type(1) > div.pf-v6-l-flex:nth-of-type(2) > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(3) > div:nth-of-type(1)";

    public static final String COPS_CLUSTER_CARD_KAFKA_WARNINGS_DROPDOWN_BUTTON = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item > div.pf-v6-l-flex > div > div.pf-v6-c-card > div.pf-v6-c-card__body > div.pf-v6-l-flex > div > div.pf-v6-c-expandable-section > div.pf-v6-c-expandable-section__toggle > button";

    public static final String COPS_CLUSTER_CARD_KAFKA_WARNING_MESSAGE_ITEMS = "body > div:nth-of-type(1) > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer:nth-of-type(2) > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(1) > div.pf-v6-c-card > div.pf-v6-c-card__body > div.pf-v6-l-flex:nth-of-type(2) > div:nth-of-type(2) > div.pf-v6-c-expandable-section > div.pf-v6-c-expandable-section__content:nth-of-type(2) > ul.pf-v6-c-data-list > li.pf-v6-c-data-list__item > div.pf-v6-c-data-list__item-row > div.pf-v6-c-data-list__item-content > div.pf-v6-c-data-list__cell:nth-of-type(2) > div:nth-of-type(1) > span.pf-v6-c-truncate > span.pf-v6-c-truncate__start";
    public static final String COPS_RECENT_TOPICS_CARD_TABLE_ITEMS = "body > div > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(2) > div.pf-v6-l-flex > div:nth-of-type(1) > div.pf-v6-c-card > div.pf-v6-c-card__expandable-content:nth-of-type(2) > div.pf-v6-c-card__body > ul.pf-v6-c-list > li";

    public static String getTableRowItemLink(int nth) {
        return new CssBuilder(COPS_RECENT_TOPICS_CARD_TABLE_ITEMS).nth(nth).build();
    }

    public static final String COPS_TOPICS_CARD_TOTAL_TOPICS = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(2) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-flex > div.pf-v6-l-flex:nth-of-type(1) > div > div.pf-v6-l-flex > div:nth-of-type(1) > div.pf-v6-c-content > small.pf-v6-c-content--small > a";

    public static final String COPS_TOPICS_CARD_TOTAL_PARTITIONS = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(2) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-flex > div.pf-v6-l-flex:nth-of-type(1) > div > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-content > small.pf-v6-c-content--small";

    public static final String COPS_TOPICS_CARD_FULLY_REPLICATED = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(2) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-flex > div.pf-v6-l-flex:nth-of-type(2) > div:nth-of-type(1)";

    public static final String COPS_TOPICS_CARD_UNDER_REPLICATED = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(2) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-flex > div.pf-v6-l-flex:nth-of-type(2) > div:nth-of-type(2)";

    public static final String COPS_TOPICS_CARD_UNAVAILABLE = "body > div#root > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(2) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-flex > div.pf-v6-l-flex:nth-of-type(2) > div:nth-of-type(3)";

    public static final String COPS_DISK_SPACE_CHART_NODE_TEXT_ITEMS = "body > div > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-stack > div.pf-v6-l-stack__item:nth-of-type(4) > div > div.pf-v6-c-chart > svg > g:nth-of-type(4) > text > tspan";

    public static final String COPS_CPU_USAGE_CHART_NODE_TEXT_ITEMS = "body > div > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-stack > div.pf-v6-l-stack__item:nth-of-type(7) > div > div.pf-v6-c-chart > svg > g:nth-of-type(4) > text > tspan";

    public static final String COPS_MEMORY_USAGE_CHART_NODE_TEXT_ITEMS = "body > div > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(1) > div.pf-v6-l-flex > div:nth-of-type(2) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-stack > div.pf-v6-l-stack__item:nth-of-type(10) > div > div.pf-v6-c-chart > svg > g:nth-of-type(4) > text > tspan";

    public static final String COPS_TOPIC_BYTES_CHART_NODE_TEXT_ITEMS = "body > div > div.pf-v6-c-page > div.pf-v6-c-page__main-container:nth-of-type(2) > main.pf-v6-c-page__main > div.pf-v6-c-drawer > div.pf-v6-c-drawer__main > div.pf-v6-c-drawer__content:nth-of-type(1) > div.pf-v6-c-drawer__body > section.pf-v6-c-page__main-section:nth-of-type(2) > div.pf-v6-c-page__main-body > div.pf-v6-l-grid > div.pf-v6-l-grid__item:nth-of-type(2) > div.pf-v6-l-flex > div:nth-of-type(3) > div.pf-v6-c-card > div.pf-v6-c-card__body:nth-of-type(2) > div.pf-v6-l-stack > div.pf-v6-l-stack__item:nth-of-type(3) > div > div > svg > g:nth-of-type(4) > text > tspan";
}
