kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-server
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkanodepools
      - kafkarebalances
      - kafkatopics
  - verbs:
      - patch
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkarebalances
  - verbs:
      - get
      - list
    apiGroups:
      - ""
    resources:
      - pods
