apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      serviceAccountName: placeholder
      volumes:
      - name: work
        emptyDir: {}
      - name: config
        secret:
          secretName: placeholder
      containers:
      ### API
      - name: console-api
        image: quay.io/streamshub/console-api
        ports:
        - containerPort: 0
          name: placeholder
        volumeMounts:
        - name: config
          mountPath: /deployments/config
          readOnly: true
        - name: work
          mountPath: /tmp
        env:
        - name: CONSOLE_CONFIG_PATH
          value: /deployments/config/console-config.yaml
        startupProbe:
          httpGet:
            path: /health/started
            port: placeholder
            scheme: placeholder
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 24
        livenessProbe:
          httpGet:
            path: /health/live
            port: placeholder
            scheme: placeholder
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: placeholder
            scheme: placeholder
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
