---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: console-controllers
  labels:
    strimzi.io/cluster: console-kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - deleteClaim: false
        id: 0
        size: 10Gi
        type: persistent-claim
