---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: console-kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  cruiseControl: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    version: 4.1.0
    authorization:
      type: simple
    config:
      allow.everyone.if.no.acl.found: 'true'
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: secure
        port: 9093
        tls: true
        type: ${LISTENER_TYPE}
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            host: bootstrap.console-kafka.${CLUSTER_DOMAIN}
            annotations:
              streamshub.github.com/console-listener: 'true'
          brokers:
          - broker: 0
            host: broker-0.console-kafka.${CLUSTER_DOMAIN}
          - broker: 1
            host: broker-1.console-kafka.${CLUSTER_DOMAIN}
          - broker: 2
            host: broker-2.console-kafka.${CLUSTER_DOMAIN}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: console-kafka-metrics
          key: kafka-metrics-config.yml
