name: Playwright Tests

on:
  workflow_call:

env:
  TARGET_NAMESPACE: "console-namespace"
  CI_CLUSTER: true

jobs:
  Test:
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set Up JDK
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
  
      - name: Cache Maven Packages
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Fetch Operator Framework Utilities
        run: ./operator/bin/fetch-operator-utilities.sh

      - name: Install skopeo
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Install minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/minikube

      - name: Create minikube cluster
        working-directory: systemtests/cluster-setup
        env:
          MINIKUBE_CPU_COUNT: '2'
          MINIKUBE_MEMORY: '8g'
          MINIKUBE_EXTRA_ADDONS: 'storage,ingress-dns,metrics-server'
          MINIKUBE_INSECURE_REGISTRY: 'localhost:5000,10.0.0.0/24'
          MINIKUBE_EXTRA_CONFIG: 'kubeadm.ignore-preflight-errors=SystemVerification;apiserver.authorization-mode=RBAC,Node'
        run: ./minikube/create-cluster.sh

      - name: Set up local registry
        working-directory: systemtests/cluster-setup
        run: ./minikube/setup-registry.sh

      - name: Build Console images from source
        working-directory: systemtests/cluster-setup
        run: ./common/build-console.sh

      - name: Load images into registry
        working-directory: systemtests/cluster-setup
        run: ./minikube/load-images.sh

      - name: Set Dynamic Environment Vars
        run: |
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          source systemtests/cluster-setup/minikube/.cluster-env
          echo "CLUSTER_DOMAIN=${CONSOLE_CLUSTER_DOMAIN}" >> $GITHUB_ENV
          echo "CONSOLE_URL=https://example-console.${CONSOLE_CLUSTER_DOMAIN}" >> $GITHUB_ENV

      - name: Deploy Strimzi, Console operator, Kafka, and Console instance
        working-directory: systemtests/cluster-setup
        run: |
          ./common/deploy-example-console.sh \
            --catalog-image "localhost:5000/streamshub/console-operator-catalog:${{ env.PROJECT_VERSION }}" \
            --kafka-namespace "${TARGET_NAMESPACE}"

      - name: Console Smoke Test
        run: |
          set -x
          curl -kL ${CONSOLE_URL}
          curl -kL ${CONSOLE_URL} | grep "StreamsHub Console"

      - name: Deploy Data Generator
        run: |
          echo '---
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: console-datagen
            spec:
              replicas: 1
              revisionHistoryLimit: 3
              selector:
                matchLabels:
                  app: console-datagen
              template:
                metadata:
                  labels:
                    app: console-datagen
                spec:
                  containers:
                  - name: console-datagen
                    image: quay.io/streamshub/console-datagen:0.5.0
                    ports:
                    - containerPort: 9080
                    livenessProbe:
                      httpGet:
                        path: /q/health/live
                        port: 9080
                        scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      successThreshold: 1
                      failureThreshold: 3
                      timeoutSeconds: 10
                    env:
                    - name: KAFKA_SECURITY_PROTOCOL
                      value: SASL_SSL
                    - name: KAFKA_SASL_MECHANISM
                      value: SCRAM-SHA-512
                    - name: DATAGEN_CONSUMER_GROUPS
                      value: "1"
                    - name: DATAGEN_TOPICS_PER_CONSUMER
                      value: "2"
                    - name: DATAGEN_PARTITIONS_PER_TOPIC
                      value: "3"
                    - name: DATAGEN_KAFKA_TEST_NAME
                      value: "TestKafka"
                    - name: DATAGEN_KAFKA_TEST_CONFIGS_BOOTSTRAP_SERVERS
                      value: "bootstrap.console-kafka.${CLUSTER_DOMAIN}:443"
                    - name: DATAGEN_KAFKA_TEST_CONFIGS_SSL_TRUSTSTORE_TYPE
                      value: PEM
                    - name: DATAGEN_KAFKA_TEST_CONFIGS_SSL_TRUSTSTORE_CERTIFICATES
                      valueFrom:
                        secretKeyRef:
                          name: console-kafka-cluster-ca-cert
                          key: ca.crt
                    - name: DATAGEN_KAFKA_TEST_CONFIGS_SASL_JAAS_CONFIG
                      valueFrom:
                        secretKeyRef:
                          key: sasl.jaas.config
                          name: console-kafka-user1' | \
            envsubst | \
            kubectl apply -n ${TARGET_NAMESPACE} -f -
          kubectl wait deployment/console-datagen --for=condition=available --timeout=300s -n $TARGET_NAMESPACE

      - name: Use Node.js
        uses: actions/setup-node@v7

      - name: Run Playwright Tests
        working-directory: ./ui
        run: |
          set -x

          npm ci
          npm ls playwright --json=true

          PLAYWRIGHT_VERSION="$(npm ls playwright --json=true | jq -r '.dependencies.playwright.version')"

          docker run --rm \
            -v$(pwd):/app:z \
            -ePLAYWRIGHT_BASE_URL="${CONSOLE_URL}" \
            -eCI_CLUSTER=true \
            --network=host \
            mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION} \
            /bin/bash -c 'cd /app && npm test'

      - name: Archive Playwright Results (failure)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: playwright-tests-failed
          path: ./ui/test-results

      - name: Backup Logs
        if: always()
        run: |
          mkdir ./logs
          kubectl logs -n operators -l strimzi.io/kind=cluster-operator --all-containers=true --tail -1 > ./logs/strimzi-cluster-operator-logs.txt
          kubectl logs -n operators -l app.kubernetes.io/name=streamshub-console-operator --all-containers=true --tail -1 > ./logs/streamshub-console-operator-logs.txt
          kubectl logs -n ${TARGET_NAMESPACE} -l app.kubernetes.io/instance=example-console-deployment --all-containers=true --tail -1 > ./logs/${TARGET_NAMESPACE}-console-logs.txt
          kubectl logs -n ${TARGET_NAMESPACE} -l app=console-datagen --all-containers=true --tail -1 > ./logs/${TARGET_NAMESPACE}-datagen-logs.txt

      - name: Archive Logs Backup
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-tests-k8s-logs
          path: ./logs

      - name: Backup Resources
        if: failure()
        run: |
          mkdir ./resources
          kubectl get all,catalogsources,operatorgroups -n olm -o yaml > ./resources/olm.yaml
          kubectl get all,subscriptions,csv,operatorgroups,installplans -n operators -o yaml > ./resources/operators.yaml
          kubectl get all,consoles,kafkas -n ${TARGET_NAMESPACE} -o yaml > ./resources/${TARGET_NAMESPACE}.yaml

      - name: Archive Resource Backup
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: playwright-tests-k8s-resources-failed
          path: ./resources
